# Import  
파이썬에서 다른 모듈이나 패키지에서 함수, 클래스 등을 가져옵니다.

In [30]:
!pip install koreanize-matplotlib
import koreanize_matplotlib


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: C:\Users\HOME\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
import numpy as np
import random
import os

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier


In [2]:
from sklearn.model_selection import train_test_split

#### 시드(seed) 고정  
매번 고정된 결과를 얻기 위해서 사용합니다.  
시드를 고정하지 않는다면 같은 코드라도 매번 다른 결과가 나올 수 있습니다.

In [3]:
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42) # Seed 고정

#### 데이터 읽어오기 및 데이터 확인

In [4]:
# pd.read_csv() 함수를 사용해서 데이터를 읽어오는 코드입니다.
train = pd.read_csv('train.csv')

# 데이터를 확인하기 위해 head() 함수를 사용합니다.
train.head()

ID   월   요일  시간  소관경찰서  소관지역    사건발생거리  강수량(mm)  강설량(mm)  적설량(cm)   
0  TRAIN_00000   9  화요일  10    137   8.0  2.611124    0.000      0.0      0.0  \
1  TRAIN_00001  11  화요일   6    438  13.0  3.209093    0.000      0.0      0.0   
2  TRAIN_00002   8  일요일   6   1729  47.0  1.619597    0.000      0.0      0.0   
3  TRAIN_00003   5  월요일   6   2337  53.0  1.921615   11.375      0.0      0.0   
4  TRAIN_00004   9  일요일  11   1439  41.0  1.789721    0.000      0.0      0.0   

      풍향   안개  짙은안개   번개  진눈깨비   서리  연기/연무  눈날림 범죄발생지  TARGET  
0  245.0  0.0   0.0  0.0   0.0  0.0    0.0  0.0    차도       2  
1  200.0  0.0   0.0  0.0   0.0  0.0    0.0  0.0    차도       0  
2   40.0  1.0   0.0  0.0   0.0  0.0    1.0  0.0    인도       1  
3  225.0  1.0   1.0  0.0   0.0  0.0    0.0  0.0   주거지       1  
4  255.0  0.0   0.0  0.0   0.0  0.0    0.0  0.0   주유소       2

#### 독립변수(x_train), 종속변수(y_train)로 분리하기  


In [5]:
x_train = train.drop(['ID', 'TARGET','진눈깨비','짙은안개'], axis = 1)
y_train = train['TARGET']


In [6]:
x_train.head()

월   요일  시간  소관경찰서  소관지역    사건발생거리  강수량(mm)  강설량(mm)  적설량(cm)     풍향   안개   
0   9  화요일  10    137   8.0  2.611124    0.000      0.0      0.0  245.0  0.0  \
1  11  화요일   6    438  13.0  3.209093    0.000      0.0      0.0  200.0  0.0   
2   8  일요일   6   1729  47.0  1.619597    0.000      0.0      0.0   40.0  1.0   
3   5  월요일   6   2337  53.0  1.921615   11.375      0.0      0.0  225.0  1.0   
4   9  일요일  11   1439  41.0  1.789721    0.000      0.0      0.0  255.0  0.0   

    번개   서리  연기/연무  눈날림 범죄발생지  
0  0.0  0.0    0.0  0.0    차도  
1  0.0  0.0    0.0  0.0    차도  
2  0.0  0.0    1.0  0.0    인도  
3  0.0  0.0    0.0  0.0   주거지  
4  0.0  0.0    0.0  0.0   주유소

#### train , validation data 나누기

In [7]:
X_tr, X_val, Y_tr, Y_val = train_test_split(x_train, y_train, test_size=0.3, random_state=42)

#### 라벨인코딩(Label Encoding) 

In [8]:

ordinal_features = ['요일', '범죄발생지']

for feature in ordinal_features:
    le = LabelEncoder()
    
    # Fit and transform on the training data
    le = le.fit(X_tr[feature])
    X_tr[feature] = le.transform(X_tr[feature])

    # Transform the test data (Note: Only transform, do not fit again to avoid data leakage)
    X_val[feature] = le.transform(X_val[feature])



In [9]:
X_tr.head()

월  요일  시간  소관경찰서  소관지역    사건발생거리  강수량(mm)  강설량(mm)  적설량(cm)     풍향   
57342   4   6  10    637  10.0  2.116536    0.000      0.0      0.0  215.0  \
5323    3   5   4    526  21.0  2.010814    0.000      0.0      0.0  145.0   
40195   9   2   2    526  21.0  2.061723    0.000      0.0      0.0   65.0   
70005  10   4   4   1926  44.0  0.535115   15.000      0.0      0.0  185.0   
36629   7   6   6   1428  33.0  0.250833    0.625      0.0      0.0  210.0   

        안개   번개   서리  연기/연무  눈날림  범죄발생지  
57342  0.0  0.0  0.0    0.0  0.0      7  
5323   1.0  0.0  0.0    1.0  0.0      7  
40195  0.0  0.0  0.0    0.0  0.0      7  
70005  1.0  1.0  0.0    1.0  0.0      7  
36629  0.0  0.0  0.0    0.0  0.0      6

#### 모델 정의

In [10]:
# 모델 인자에 random_state를 넣음으로써 시드고정의 효과를 얻을 수 있습니다.
rf_model = RandomForestClassifier(random_state=42)

#### 모델 학습

In [11]:
rf_model.fit(X_tr, Y_tr)

RandomForestClassifier(random_state=42)

#### 예측

In [12]:
# predict() 함수는 독립변수(테스트데이터)를 입력받았을 때 종속변수를 예측합니다.
pred = rf_model.predict(X_val)

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

acc=accuracy_score(Y_val,pred)
print(f'정확도 : {acc:.4f}')

# 정밀도 (precision)
precision=precision_score(Y_val,pred, average='weighted')
print(f'정말도 : {precision:.4f}')

recall = recall_score(Y_val, pred, average='weighted')  # 다중 클래스인 경우 average 설정
print(f'Recall: {recall:.4f}')

# F1 점수 (F1 Score)
f1 = f1_score(Y_val, pred, average='weighted')  # 다중 클래스인 경우 average 설정
print(f'F1 Score: {f1:.4f}')

# 혼동 행렬 (Confusion Matrix)
conf_matrix = confusion_matrix(Y_val, pred)
print('Confusion Matrix:')
print(conf_matrix)

정확도 : 0.5263
정말도 : 0.5188
Recall: 0.5263
F1 Score: 0.5159
Confusion Matrix:
[[7567 1696 1656]
 [2942 3510 1190]
 [3242 1269 2250]]
